version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/klartext/frontend
      - /klartext/frontend/node_modules
    environment:
      - PORT=5000
      
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    image: klartext_backend:dev
    volumes:
      - ./backend:/klartext/backend
      - ./backend/.gradle:/klartext/backend/.gradle
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - db
      - es
    environment:
      - DB_URL=jdbc:mysql://db:3306/klartext?verifyServerCertificate=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Stockholm
      - DB_USER=root
      - DB_PASSWORD=chuansu
      - ES_CLUSTER_NAME=klartext_cluster
      - ES_NODE_HOST=es
      
  ruby:
    build: ./ruby-scripts
    volumes:
      - ./ruby-scripts:/klartext/ruby-scripts
    depends_on:
      - db
      - es
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: chuansu
      
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: chuansu
      MYSQL_DATABASE: klartext
      MYSQL_USER: root
      MYSQL_PASSWORD: chuansu
      
  es:
    build: ./es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es/esdata:/usr/share/elasticsearch/data
