version: '2'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - elasticsearch
  db:
    image: mysql:latest
  elasticsearch:
    image: elasticsearch:latest
